import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, LockKeyhole, Mail, Wrench } from 'lucide-react'
import { api } from '../services/api'

export default function Login(){
  const navigate=useNavigate(); const [email,setEmail]=useState('admin@serviceflow.dev'); const [password,setPassword]=useState('123456'); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setError('');setLoading(true);try{const r=await api.post('/auth/login',{email,password});localStorage.setItem('serviceflow_token',r.data.token);localStorage.setItem('serviceflow_user',JSON.stringify(r.data.user));navigate('/')}catch(err:any){setError(err.response?.data?.error||'Não foi possível entrar')}finally{setLoading(false)}}
  return <div className="login-page"><div className="login-visual"><div className="visual-inner"><div className="brand light"><div className="brand-mark">S</div><div><strong>ServiceFlow</strong><small>Gestão de serviços</small></div></div><div className="visual-copy"><span className="pill">FULL STACK PORTFOLIO</span><h1>Transforme chamados em uma operação organizada.</h1><p>Dashboard, clientes, equipamentos, ordens de serviço, orçamentos e financeiro em um só lugar.</p></div><div className="visual-card"><Wrench size={22}/><div><strong>Operação centralizada</strong><span>Acompanhe cada serviço do recebimento à entrega.</span></div></div></div></div><div className="login-panel"><div className="login-form"><span className="eyebrow">Acesso seguro</span><h2>Entrar no ServiceFlow</h2><p className="muted">Use a conta de demonstração para explorar o sistema.</p><form onSubmit={submit}><label>E-mail<div className="input-icon"><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} /></div></label><label>Senha<div className="input-icon"><LockKeyhole size={17}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} /></div></label>{error&&<div className="alert error">{error}</div>}<button className="primary-btn" disabled={loading}>{loading?'Entrando...':'Entrar'}<ArrowRight size={18}/></button></form><div className="demo-box"><span>DEMO</span><strong>admin@serviceflow.dev</strong><small>Senha: 123456</small></div></div></div></div>
}
